baseURL: "https://osorensen.github.io" 
title: Øystein Sørensen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Software
          url: software/
          weight: 2
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 3                

params:
    description: |
        I am a Professor of Statistics in the Department of Psychology at the University of Oslo, Norway.
        I am interested in latent variable models for analysis of longitudinal data in psychology,
        particularly on developing efficient computational algorithms and software.
        I also work on interpretable machine learning methods, and through various collaborations
        I am involved in a range of applied projects in psychology and neuroscience.
    author: Øystein Sørensen
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers","software"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Øystein Sørensen
          subtitle: "I am a Professor of Statistics in the Department of Psychology at the University of Oslo, Norway. I am interested in latent variable models for analysis of longitudinal data in psychology, particularly on developing efficient computational algorithms and software. I also work on interpretable machine learning methods, and through various collaborations I am involved in a range of applied projects in psychology and neuroscience."
          imageUrl: "picture.jpeg"          
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Software
              url: software/
            - name: Courses
              url: courses/                        
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/            

    socialIcons:        
        - name: Email
          url: mailto:oystein.sorensen@psykologi.uio.no        
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=no&user=neOqbw0AAAAJ&view_op=list_works&sortby=pubdate
        - name: GitHub
          url: https://github.com/osorensen
        - name: LinkedIn
          url: www.linkedin.com/in/øystein-sørensen-4b487626b
        - name: Bluesky
          url: https://bsky.app/profile/osorensen.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Øystein Sørensen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2