baseURL: "https://osorensen.github.io" 
title: Øystein Sørensen

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: /#research
          weight: 2
        - name: Publications
          url: papers/
          weight: 3
        - name: Software
          url: software/
          weight: 4
        - name: Courses
          url: courses/
          weight: 6
        - name: Contact
          url: /#contact
          weight: 7

params:
    description: "Academic profile for Øystein Sørensen."
    author: Øystein Sørensen
    role: Professor of Statistics
    affiliation: Department of Psychology, University of Oslo
    email: oystein.sorensen@psykologi.uio.no
    profileImage: picture.jpeg
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers","software"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Øystein Sørensen
          subtitle: '{{< profile_subtitle >}}'
          imageUrl: "picture.jpeg"          
          imageHeight: 160
          imageWidth: 120
          buttons:
            - name: Papers
              url: papers/
            - name: Software
              url: software/
            - name: Courses
              url: courses/                        
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/            

    socialIcons:        
        - name: Email
          url: mailto:oystein.sorensen@psykologi.uio.no        
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=no&user=neOqbw0AAAAJ&view_op=list_works&sortby=pubdate
        - name: GitHub
          url: https://github.com/osorensen
        - name: LinkedIn
          url: https://www.linkedin.com/in/øystein-sørensen-4b487626b
        - name: Bluesky
          url: https://bsky.app/profile/osorensen.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Øystein Sørensen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
